# Generated by Django 5.2.8 on 2025-11-24 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubtitleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(help_text='Например, "en", "ru"', max_length=10, verbose_name='Язык субтитров')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitle_sets', to='films.film', verbose_name='Фильм')),
            ],
            options={
                'verbose_name': 'Набор субтитров',
                'verbose_name_plural': 'Наборы субтитров',
                'unique_together': {('film', 'language')},
            },
        ),
        migrations.CreateModel(
            name='SubtitleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.FloatField(help_text='Время в секундах, с точностью до миллисекунд.', verbose_name='Время начала (с)')),
                ('end_time', models.FloatField(verbose_name='Время окончания (с)')),
                ('text', models.TextField(verbose_name='Текст субтитра')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя персонажа')),
                ('style_classes', models.CharField(blank=True, help_text='Например: "bold italic red-text"', max_length=255, null=True, verbose_name='Классы стилей')),
                ('subtitle_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='films.subtitleset', verbose_name='Набор субтитров')),
            ],
            options={
                'verbose_name': 'Строка субтитра',
                'verbose_name_plural': 'Строки субтитров',
                'ordering': ['start_time', 'end_time'],
            },
        ),
    ]
