# Generated by Django 5.2.8 on 2025-11-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_subtitleset_subtitleline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtitleline',
            name='style_classes',
        ),
        migrations.AddField(
            model_name='subtitleline',
            name='style',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subtitleset',
            name='language',
            field=models.CharField(help_text='Например, "en", "ru"', max_length=2, verbose_name='Язык субтитров'),
        ),
    ]
