# Generated by Django 5.2.8 on 2025-11-29 19:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_remove_subtitleline_style_classes_subtitleline_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtitleline',
            name='end_time',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Время окончания (с)'),
        ),
        migrations.AlterField(
            model_name='subtitleline',
            name='start_time',
            field=models.FloatField(help_text='Время в секундах, с точностью до миллисекунд.', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Время начала (с)'),
        ),
    ]
