# Generated by Django 5.2.8 on 2025-11-29 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_alter_subtitleline_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitleset',
            name='speaker_color_map',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"Имя Персонажа": "#HEX_ЦВЕТ", "Другое Имя": "#HEX_ЦВЕТ", ...}', verbose_name='Карта цветов персонажей'),
        ),
    ]
