# Generated by Django 5.2.8 on 2025-12-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_subtitleset_speaker_color_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtitleline',
            name='style',
        ),
        migrations.AddField(
            model_name='subtitleline',
            name='style_classes',
            field=models.CharField(blank=True, default='', help_text='Классы через пробел, например: bold shadow', max_length=255, verbose_name='Классы стилей CSS'),
        ),
    ]
