# Generated by Django 5.2.8 on 2025-12-08 09:53

import films.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_remove_subtitleline_style_subtitleline_style_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtitleline',
            name='style_classes',
            field=models.CharField(blank=True, default='', help_text='Классы через пробел, например: bold loud', max_length=255, verbose_name='Классы стилей CSS'),
        ),
        migrations.AlterField(
            model_name='subtitleset',
            name='language',
            field=models.CharField(help_text='Например, "en", "ru"', max_length=2, validators=[films.validators.LanguageCodeValidator], verbose_name='Язык субтитров'),
        ),
    ]
